engines:
 rubocop:
   enabled: false
 duplication:
   enabled: true
 metrics:
   enabled: true
 coverage:
   enabled: false
exclude_paths:
  - thinx-esp8266-example/lib/ArduinoJson/**
  - thinx-esp8266-example/lib/PubSubClient/**
  - thinx-esp8266-example/lib/WiFiManager/**